### ISSUE TITLE
我就想测试个问题这么难吗？

### ISSUE THREAD

**Issue by ghost** [actions/starter-workflows#1029]
Thank you 🙇‍♀ for wanting to create an issue in this repository. Before you do, please ensure you are filing the issue in the right place. Issues should only be opened on if the issue **relates to code in this repository**.

* If you have found a security issue [please submit it here](https://hackerone.com/github)
* If you have questions about writing workflows or action files, then please [visit the GitHub Community Forum's Actions Board](https://github.community/c/code-to-cloud/github-actions)
* If you are having an issue or question about GitHub Actions then please [contact customer support](https://help.github.com/en/articles/about-github-actions#contacting-support)

If your issue is relevant to this repository, please delete this text and continue to create this issue. Thank you in advance.

**Comment by 7xsw** [comment]
我就想测试一个问题

**Comment by jeecee59** [comment]
Flikker op stelletje tering zeikers. Ik wil deze wtf rotzooi niet langer en ik creeer zo een heel groot probleem en bombardeer de hele tering zooi daar bij jullie: DUS IK EIS NU OOK ER DIRECT DAT JULLIE MIJ UITSCHRIJVEN ZO NIET KOM IK MET MIJN GEHUURD PERSONEEL EN GAAT ALLES ER AAN INCLUSIEF JULLIE ZELF 🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕🖕

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: 7xsw ***@***.***>
Verzonden: Saturday, July 31, 2021 11:33:53 AM
Aan: actions/starter-workflows ***@***.***>
CC: Subscribed ***@***.***>
Onderwerp: [actions/starter-workflows] 我就想测试个问题这么难吗？ (#1029)


Thank you 🙇‍♀ for wanting to create an issue in this repository. Before you do, please ensure you are filing the issue in the right place. Issues should only be opened on if the issue relates to code in this repository.

  *   If you have found a security issue please submit it here<https://hackerone.com/github>
  *   If you have questions about writing workflows or action files, then please visit the GitHub Community Forum's Actions Board<https://github.community/c/code-to-cloud/github-actions>
  *   If you are having an issue or question about GitHub Actions then please contact customer support<https://help.github.com/en/articles/about-github-actions#contacting-support>

If your issue is relevant to this repository, please delete this text and continue to create this issue. Thank you in advance.
