### ISSUE TITLE
我想建立一个新任务

### ISSUE THREAD

**Issue by 7xsw** [actions/starter-workflows#1030]
Thank you 🙇‍♀ for wanting to create an issue in this repository. Before you do, please ensure you are filing the issue in the right place. Issues should only be opened on if the issue **relates to code in this repository**.

* If you have found a security issue [please submit it here](https://hackerone.com/github)
* If you have questions about writing workflows or action files, then please [visit the GitHub Community Forum's Actions Board](https://github.community/c/code-to-cloud/github-actions)
* If you are having an issue or question about GitHub Actions then please [contact customer support](https://help.github.com/en/articles/about-github-actions#contacting-support)

If your issue is relevant to this repository, please delete this text and continue to create this issue. Thank you in advance.

**Comment by 7xsw** [comment]
这个任务可以吗？

**Comment by jeecee59** [comment]
Flikker op stelletje tering zeikers. Ik wil deze wtf rotzooi niet langer en ik creeer zo een heel groot probleem en bombardeer de hele tering zooi daar bij jullie: DUS IK EIS NU OOK ER DIRECT DAT JULLIE MIJ UITSCHRIJVEN ZO NIET KOM IK MET MIJN GEHUURD PERSONEEL EN GAAT ALLES ER AAN INCLUSIEF JULLIE ZELF

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: 7xsw ***@***.***>
Verzonden: Saturday, July 31, 2021 11:39:50 AM
Aan: actions/starter-workflows ***@***.***>
CC: Subscribed ***@***.***>
Onderwerp: [actions/starter-workflows] 我想建立一个新任务 (#1030)


Thank you 🙇‍♀ for wanting to create an issue in this repository. Before you do, please ensure you are filing the issue in the right place. Issues should only be opened on if the issue relates to code in this repository.

  *   If you have found a security issue please submit it here<https://hackerone.com/github>
  *   If you have questions about writing workflows or action files, then please visit the GitHub Community Forum's Actions Board<https://github.community/c/code-to-cloud/github-actions>
  *   If you are having an issue or question about GitHub Actions then please contact customer support<https://help.github.com/en/articles/about-github-actions#contacting-support>

If your issue is relevant to this repository, please delete this text and continue to create this issue. Thank you in advance.

**Comment by Mythrandyr559** [comment]
My first thing,  this seems so difficult.  The options are a sham,  the
ease odd use is a multiple formula equation. That nor sols, nor baught.
bought. Is is not valuable it is invaluable, priceless.  Nor ready to
commit to non sense, I'll keep eyes open And seer what I get

**Comment by jeecee59** [comment]
Kop dicht ben dit gezeik zat het is verd net een sekte waar mensen ook bijna niet vanaf kunnen komen en uiteindelijk zwaar geschut in moeten zetten en dit via gerechterlijke weg middels een strafrechtelijke procedure/proces los kunnen komen van dat sektarisch gespam. En de veroorzakers een beste schadeclaim aan hun dikke reten en piemels geven. En als ze dan nog niet stoppen er zelf op af gaan en zelf de hand aan die misdadigers slaan. En als JULLIE NU NIET OPHOUDEN ZIJN JULLIE AAN DE BEURT EN ZIJN JULLIE DE LUL EN DE KUT!!!!
WHEN YOU WILL KNOWING WHAT I SEND YOU IN MY DUTCH LANGUAGE THEN YOU MUST TRANSLATE IT ON GOOGLE. En i mean all the words is send to you. You are really the same as a sekte. AND I COMMIT YOU FOR THE LAST TIME STOP WITH E-MAIL ME AND GET MY E-MAIL GESTUURD OUT OF YOURE DATABASE.
AND I COMMIT YOU LIKE THIS WAY TO UNSUBSCRIBE ME FROM THE MAILING LIST YOU ARE VERY IDIOT STUPID KUT PEOPLE

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: Adam Lynn Pritchard ***@***.***>
Verzonden: Saturday, July 31, 2021 1:26:10 PM
Aan: actions/starter-workflows ***@***.***>
CC: jeecee59 ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [actions/starter-workflows] 我想建立一个新任务 (#1030)


My first thing, this seems so difficult. The options are a sham, the
ease odd use is a multiple formula equation. That nor sols, nor baught.
bought. Is is not valuable it is invaluable, priceless. Nor ready to
commit to non sense, I'll keep eyes open And seer what I get
