### ISSUE TITLE
Reusable workflow

### ISSUE THREAD

**Issue by neilime** [actions/starter-workflows#1807]
These starter workflows are great and well maintained.

IMO, there is a pain with keeping up to date these workflow once there copied / pasted into ours. We need to look for updates manually, then copy / paste again... Not so easy!

It will be great to make them reusable (https://docs.github.com/en/actions/using-workflows/reusing-workflows#creating-a-reusable-workflow) in order to used them in our workflows without copy/past and then take advantage of updates with upgrading tag 

Combining with dependabot and "GitHub Actions" package ecosystem configuration, update management will be so easy!

Thank you

**Comment by bishal-pdMSFT** [comment]
That's a really good point @neilime. 

We don't have anything currently on this. It has though come up in couple of discussions. One of the disadvantage here would be more complexity (due to loss of readability and clarity) to the user as they won't know the details behind reusable workflow. 

cc @ashokirla
