### ISSUE TITLE
add pandoc project workflow

### ISSUE THREAD

**Issue by maxheld83** [actions/starter-workflows#28]
Pandoc is a universal document converter, and is often used by people who just want to write (pandoc's) markdown document and have them converted and published to a number of outputs.

I think quite a lot of people use this to convert `*.md` sources in a repo and publish it to GitHub Pages.

A default workflow would be nice for that.

Would be happy to hack that together, it's pretty simple.

Would you accept a PR for that?

**Comment by chrispat** [comment]
@maxheld83 I think running pandoc would really be a better choice for an action rather than a whole workflow.  That way people can compose it into their workflows as it makes sense.  For more details about creating an action take a look at https://github.com/actions/toolkit/blob/master/docs/javascript-action.md.
