### ISSUE TITLE
skip building

### ISSUE THREAD

**Issue by dmodoomsirius** [actions/starter-workflows#286]
Ability to skip building a workflow if you have something on [push] would be great. especially if you are updating other workflow's

**Comment by udeathstarck** [comment]
Run

**Comment by ethomson** [comment]
Hi @dmodoomsirius - I'm afraid this is the issue and bug tracker for the starter workflows (the templates that we offer you when you create a new GitHub Actions workflow).

This seems like a great suggestion for the [GitHub Community Forum](https://github.community/t5/GitHub-Actions/bd-p/actions).  This is a place where the support team and product managers for GitHub Actions will be happy to review your suggestion.

Accordingly, since there's no bug in the workflow templates, I'm going to close this issue.

**Comment by udeathstarck** [comment]
Unsubscribe
